### ISSUE TITLE
Doesn't install correctly using r2modman-dsp

### ISSUE THREAD

**Issue by Windows10CE** [TheHologram/unity-console#2] opened 2021-02-14 19:51 UTC
The directory BepInEx in your ZIP file doesn't resolve correctly, and everything gets put into the plugins folder. Making your own directories in the BepInEx folder is considered bad practice, and as such r2modman doesn't support it. https://dsp.thunderstore.io/package/TheHologram/PythonCheats/

**Comment by TheHologram** [comment] 2021-02-18 00:46
And expecting modders to use BepInEx.dll which does not bind to expected unity runtime platform assets for versions of unity that are 3+ years old is not good behavior either.  Putting all of your junk in a single folder and not having optinos for subfolders is also not good behavior but I guess the some developers get to enforce the rules they like.

Having said that the issue is resolved in the distribution posted to thundermods because it can work that way if configured for it.

**Closed as completed by TheHologram** 2021-02-18 00:46 UTC

**Comment by ebkr** [comment] 2021-02-18 22:56
Aware that it's closed but BepInEx does support subfolders. Not sure why you thought it didn't?
`/BepInEx/plugins/TheHologram-PythonCheats/Console/xyz` is fine.

**Comment by ebkr** [comment] 2021-02-18 23:02
> Putting all of your junk in a single folder and not having optinos for subfolders is also not good behavior but I guess the some developers get to enforce the rules they like.

r2modman supports all standard BepInEx folders for packaging your mod. It allows you to place items in /plugins, /config, /core, /monomod and /patchers.
(See: https://github.com/ebkr/r2modmanPlus/wiki/Structuring-your-Thunderstore-package)

I'm more than happy to support the Console folder if there's a technical reason behind it, such as BepInEx actually looking in that folder during startup.
If it's _required_ for BepInEx to use it (and not possible using the plugins folder), then that's fine.

If it can be and is just a place for you to store things because of preference, then no. A standard format is far nicer than polluting the BepInEx folder.
